/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-05-13 15:49:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class muutaasiakas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<script src=\"scripts/main.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n");
      out.write("<title>Asiakkaan muokkaus</title>\n");
      out.write("</head>\n");
      out.write("<body onkeydown=\"tutkiKey(event)\">\n");
      out.write("<form id=\"tiedot\">\n");
      out.write("\t<table id=\"lisays\">\n");
      out.write("\t\t<thead>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th colspan=\"3\" id=\"ilmo\"></th>\n");
      out.write("\t\t\t<th colspan=\"2\" class=\"oikealle\"><a href=\"listaaasiakkaat.jsp\" id=\"takaisin\">Takaisin listaukseen</a></th>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<th class=\"vasemmalle\">Etunimi</th>\n");
      out.write("\t\t\t\t<th class=\"vasemmalle\">Sukunimi</th>\n");
      out.write("\t\t\t\t<th class=\"vasemmalle\">Puhelin</th>\n");
      out.write("\t\t\t\t<th class=\"vasemmalle\">Sähköposti</th>\n");
      out.write("\t\t\t\t<th class=\"vasemmalle\"></th>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</thead>\n");
      out.write("\t\t\n");
      out.write("\t\t<tbody>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"Etunimi\" id=\"Etunimi\"></td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"Sukunimi\" id=\"Sukunimi\"></td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"Puhelin\" id=\"Puhelin\"></td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"Sposti\" id=\"Sposti\"></td>\n");
      out.write("\t\t\t\t<td><input type=\"button\" id=\"tallenna\" value=\"Hyväksy\" onclick=\"vieTiedot()\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</tbody>\n");
      out.write("\t</table>\n");
      out.write("\t<input type=\"hidden\" name=\"asiakas_id\" id=\"asiakas_id\">\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("document.getElementById(\"Etunimi\").focus();\n");
      out.write("\n");
      out.write("function tutkiKey(event) {\n");
      out.write("\tif(event.keyCode==13) {\n");
      out.write("\t\tvieTiedot();\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("var asiakas_id = requestURLParam(\"asiakas_id\");\n");
      out.write("fetch(\"asiakkaat/haeyksi/\" + asiakas_id,{\n");
      out.write("\tmethod: 'GET'\n");
      out.write("})\n");
      out.write(".then (function (response){\n");
      out.write("\treturn response.json()\n");
      out.write("})\n");
      out.write(".then (function (responseJson){\n");
      out.write("\tdocument.getElementById(\"asiakas_id\").value = responseJson.asiakas_id;\n");
      out.write("\tdocument.getElementById(\"Etunimi\").value = responseJson.etunimi;\n");
      out.write("\tdocument.getElementById(\"Sukunimi\").value = responseJson.sukunimi;\n");
      out.write("\tdocument.getElementById(\"Puhelin\").value = responseJson.puhelin;\n");
      out.write("\tdocument.getElementById(\"Sposti\").value = responseJson.sposti;\n");
      out.write("});\n");
      out.write("\n");
      out.write("function vieTiedot(){\n");
      out.write("\tvar ilmo=\"\";\n");
      out.write("\tif(document.getElementById(\"Etunimi\").value.length<3){\n");
      out.write("\t\tilmo=\"Etunimi ei kelpaa!\";\t\t\n");
      out.write("\t}\n");
      out.write("\telse if(document.getElementById(\"Sukunimi\").value.length<3){\n");
      out.write("\t\tilmo=\"Sukunimi ei kelpaa!\";\t\t\n");
      out.write("\t}\n");
      out.write("\telse if(document.getElementById(\"Puhelin\").value.length<5){\n");
      out.write("\t\tilmo=\"Puhelinnumero ei kelpaa!\";\t\t\n");
      out.write("\t}\n");
      out.write("\telse if(document.getElementById(\"Puhelin\").value*1!=document.getElementById(\"Puhelin\").value){\n");
      out.write("\t\tilmo=\"Puhelin ei ole numeroarvo!\";\t\t\n");
      out.write("\t}\n");
      out.write("\telse if(document.getElementById(\"Sposti\").value.length<5){\n");
      out.write("\tilmo=\"Sähköposti ei kelpaa!\";\t\t\n");
      out.write("\t}\n");
      out.write("\tif(ilmo!=\"\"){\n");
      out.write("\t\tdocument.getElementById(\"ilmo\").innerHTML=ilmo;\n");
      out.write("\t\tsetTimeout(function() { document.getElementById(\"ilmo\").innerHTML=\"\"; }, 3000);\n");
      out.write("\t\treturn;\n");
      out.write("\t}\n");
      out.write("\tdocument.getElementById(\"Etunimi\").value=siivoa(document.getElementById(\"Etunimi\").value);\n");
      out.write("\tdocument.getElementById(\"Sukunimi\").value=siivoa(document.getElementById(\"Sukunimi\").value);\n");
      out.write("\tdocument.getElementById(\"Puhelin\").value=siivoa(document.getElementById(\"Puhelin\").value);\n");
      out.write("\tdocument.getElementById(\"Sposti\").value=siivoa(document.getElementById(\"Sposti\").value);\n");
      out.write("\t\n");
      out.write("\tvar formJsonStr=formDataJsonStr(document.getElementById(\"tiedot\"));\n");
      out.write("\tconsole.log(formJsonStr);\n");
      out.write("\tfetch(\"asiakkaat\",{\n");
      out.write("\t\tmethod: 'PUT',\n");
      out.write("\t\tbody:formJsonStr\n");
      out.write("\t})\n");
      out.write("\t.then(function (response){\n");
      out.write("\t\treturn response.json()\n");
      out.write("\t})\n");
      out.write("\t.then(function (responseJson) {\n");
      out.write("\t\tvar vastaus = responseJson.response;\n");
      out.write("\t\tif(vastaus==0){\n");
      out.write("\t\t\tdocument.getElementById(\"ilmo\").innerHTML = \"Asiakkaan päivitys epäonnistui\";\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(vastaus==1){\n");
      out.write("\t\t\tdocument.getElementById(\"ilmo\").innerHTML = \"Asiakkaan päivitys onnistui\";\n");
      out.write("\t\t}\n");
      out.write("\t\tsetTimeout(function(){ document.getElementById(\"ilmo\").innerHTML=\"\"; }, 5000);\n");
      out.write("\t});\n");
      out.write("\tdocument.getElementById(\"tiedot\").reset();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
